### ISSUE TITLE
All my save files have been changed from "Random" encounter mode to "Field" encounter mode

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#785] opened 2022-10-05 16:34 UTC
I also noticed when starting up a new game that "Field" is the first/default option, and that "Random" is the second option, now. I wonder if something that was changed around the time this happened had something to do with it?

**Comment by psywombats** [comment] 2022-10-06 02:56
Should be fixed in the latest build. Was indeed caused by that reordering.

**Closed by psywombats** 2022-10-06 02:56 UTC
Labels: bug
