### ISSUE TITLE
World 3 - Game softlocked after killing Drone (R) with SAW

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#367] opened 2020-07-01 01:19 UTC
Below is the log. For reference, Drone (L) was dead, and MACHINE had already acted this turn.

NullReferenceException: Object reference not set to an instance of an object
Intent+<ResolveAsync>d__43.MoveNext () (at Assets/Scripts/RPG/Intent.cs:90)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
Battle+<ResolveIntentsAsync>d__55.MoveNext () (at Assets/Scripts/RPG/Battle.cs:337)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
Battle+<FightAsync>d__51.MoveNext () (at Assets/Scripts/RPG/Battle.cs:231)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
Battle+<BattleAsync>d__50.MoveNext () (at Assets/Scripts/RPG/Battle.cs:166)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
Battle+<StartBattleAsync>d__49.MoveNext () (at Assets/Scripts/RPG/Battle.cs:152)
Rethrow as AggregateException: One or more errors occurred.
CoUtils+<TaskAsRoutine>d__9.MoveNext () (at Assets/Scripts/Util/CoUtils.cs:96)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)

**Comment by psywombats** [comment] 2020-07-01 01:34
/think/ this was an NRE caused by a null effect, should be fixed

**Closed** 2020-07-07 15:44 UTC
